### ISSUE TITLE
ReferenceError: body is not defined

### ISSUE THREAD

**Issue by Kowus** [nomad-inc/theodore#3]
/app/app.js:60
```javascript
let msg = `there are ${body.total_count} projects on ${topic}`;
```
ReferenceError: body is not defined 
    at github.search.repos (/app/app.js:60:44) 
    at /app/node_modules/github/lib/index.js:906:9 
    at callCallback (/app/node_modules/github/lib/index.js:732:9) 
    at IncomingMessage.<anonymous> (/app/node_modules/github/lib/index.js:804:13) 
    at emitNone (events.js:91:20) 
    at IncomingMessage.emit (events.js:185:7) 
    at endReadableNT (_stream_readable.js:974:12) 
    at _combinedTickCallback (internal/process/next_tick.js:80:11) 
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by Kowus** [comment]
Fixed in commit [ea9af28](https://github.com/nomad-inc/theodore/commit/ea9af289f627ddeeded80ffb69f2dde6868c2f1e)
